export const incidentManagementData = [
    {   
        "officeId": "OFC0001",
        "tripId": "TRIP0001",
        "dateOfIncident": "20240712",
        "timeOfIncident": "09:30",
        "incidentLocation": "Noida",
        "vendorName": "World Travels",
        "vehicleNo": "DL000779",
        "driverName": "Tom",
        "status": "Under Investigation",
        "major": "7",
        "minor": "1",
        "noInjury": "0"
    },
    {   
        "officeId": "OFC0002",
        "tripId": "TRIP0002",
        "dateOfIncident": "20240712",
        "timeOfIncident": "10:15",
        "incidentLocation": "Gurgaon",
        "vendorName": "City Tours",
        "vehicleNo": "HR001234",
        "driverName": "Alice",
        "status": "Closed",
        "major": "2",
        "minor": "0",
        "noInjury": "1"
    },
    {   
        "officeId": "OFC0003",
        "tripId": "TRIP0003",
        "dateOfIncident": "20240712",
        "timeOfIncident": "08:45",
        "incidentLocation": "Delhi",
        "vendorName": "Metro Travels",
        "vehicleNo": "UP5678",
        "driverName": "John",
        "status": "Open",
        "major": "5",
        "minor": "3",
        "noInjury": "0"
    },
    {   
        "officeId": "OFC0004",
        "tripId": "TRIP0004",
        "dateOfIncident": "20240712",
        "timeOfIncident": "11:30",
        "incidentLocation": "Mumbai",
        "vendorName": "Ocean Tours",
        "vehicleNo": "MH98765",
        "driverName": "Emma",
        "status": "Under Investigation",
        "major": "4",
        "minor": "2",
        "noInjury": "0"
    },
    {   
        "officeId": "OFC0005",
        "tripId": "TRIP0005",
        "dateOfIncident": "20240712",
        "timeOfIncident": "09:00",
        "incidentLocation": "Bangalore",
        "vendorName": "Greenways",
        "vehicleNo": "KA4321",
        "driverName": "David",
        "status": "Closed",
        "major": "1",
        "minor": "0",
        "noInjury": "1"
    },
    {   
        "officeId": "OFC0006",
        "tripId": "TRIP0006",
        "dateOfIncident": "20240712",
        "timeOfIncident": "10:45",
        "incidentLocation": "Chennai",
        "vendorName": "Sunrise Tours",
        "vehicleNo": "TN8765",
        "driverName": "Sophia",
        "status": "Open",
        "major": "3",
        "minor": "1",
        "noInjury": "0"
    },
    {   
        "officeId": "OFC0007",
        "tripId": "TRIP0007",
        "dateOfIncident": "20240712",
        "timeOfIncident": "08:00",
        "incidentLocation": "Hyderabad",
        "vendorName": "Star Travels",
        "vehicleNo": "AP5432",
        "driverName": "Michael",
        "status": "Closed",
        "major": "2",
        "minor": "0",
        "noInjury": "1"
    },
    {   
        "officeId": "OFC0008",
        "tripId": "TRIP0008",
        "dateOfIncident": "20240712",
        "timeOfIncident": "11:15",
        "incidentLocation": "Pune",
        "vendorName": "Hilltop Travels",
        "vehicleNo": "MH1234",
        "driverName": "Olivia",
        "status": "Under Investigation",
        "major": "6",
        "minor": "2",
        "noInjury": "0"
    },
    {   
        "officeId": "OFC0009",
        "tripId": "TRIP0009",
        "dateOfIncident": "20240712",
        "timeOfIncident": "09:15",
        "incidentLocation": "Kolkata",
        "vendorName": "Eastern Routes",
        "vehicleNo": "WB9876",
        "driverName": "Daniel",
        "status": "Open",
        "major": "4",
        "minor": "0",
        "noInjury": "0"
    },
    {   
        "officeId": "OFC0010",
        "tripId": "TRIP0010",
        "dateOfIncident": "20240712",
        "timeOfIncident": "10:30",
        "incidentLocation": "Jaipur",
        "vendorName": "Royal Travels",
        "vehicleNo": "RJ5678",
        "driverName": "Sophie",
        "status": "Closed",
        "major": "3",
        "minor": "1",
        "noInjury": "1"
    }
];
