export const liveTrackingData = [
    {   
        "vehicleNo": "DL000779",
        "tripId": "TRIP0001",
        "shiftTime": "09:30",
        "shiftType": "Login",
        "employee": "12",
        "tripStartTime": "07:45",
        "route": "Rohini, East Delhi",
        "office": "7",
        "eta": "1",
        "vehicleType": "Cab"
    },
    {   
        "vehicleNo": "HR001234",
        "tripId": "TRIP0002",
        "shiftTime": "10:00",
        "shiftType": "Logout",
        "employee": "10",
        "tripStartTime": "09:15",
        "route": "Gurgaon, Cyber City",
        "office": "5",
        "eta": "2",
        "vehicleType": "Sedan"
    },
    {   
        "vehicleNo": "UP5678",
        "tripId": "TRIP0003",
        "shiftTime": "08:45",
        "shiftType": "Login",
        "employee": "15",
        "tripStartTime": "08:00",
        "route": "Noida, Sector 62",
        "office": "8",
        "eta": "1.5",
        "vehicleType": "Minivan"
    },
    {   
        "vehicleNo": "MH98765",
        "tripId": "TRIP0004",
        "shiftTime": "11:15",
        "shiftType": "Login",
        "employee": "8",
        "tripStartTime": "10:30",
        "route": "Mumbai, Bandra Kurla Complex",
        "office": "6",
        "eta": "3",
        "vehicleType": "SUV"
    },
    {   
        "vehicleNo": "KA4321",
        "tripId": "TRIP0005",
        "shiftTime": "09:00",
        "shiftType": "Logout",
        "employee": "11",
        "tripStartTime": "08:15",
        "route": "Bangalore, Whitefield",
        "office": "7",
        "eta": "1.8",
        "vehicleType": "Hatchback"
    },
    {   
        "vehicleNo": "TN8765",
        "tripId": "TRIP0006",
        "shiftTime": "10:45",
        "shiftType": "Login",
        "employee": "13",
        "tripStartTime": "10:00",
        "route": "Chennai, T Nagar",
        "office": "9",
        "eta": "2.5",
        "vehicleType": "Sedan"
    },
    {   
        "vehicleNo": "AP5432",
        "tripId": "TRIP0007",
        "shiftTime": "08:00",
        "shiftType": "Logout",
        "employee": "9",
        "tripStartTime": "07:30",
        "route": "Hyderabad, HITEC City",
        "office": "6",
        "eta": "1.2",
        "vehicleType": "Cab"
    },
    {   
        "vehicleNo": "MH1234",
        "tripId": "TRIP0008",
        "shiftTime": "11:30",
        "shiftType": "Login",
        "employee": "14",
        "tripStartTime": "11:00",
        "route": "Pune, Magarpatta City",
        "office": "8",
        "eta": "2",
        "vehicleType": "Minivan"
    },
    {   
        "vehicleNo": "WB9876",
        "tripId": "TRIP0009",
        "shiftTime": "09:15",
        "shiftType": "Login",
        "employee": "10",
        "tripStartTime": "08:30",
        "route": "Kolkata, Salt Lake City",
        "office": "5",
        "eta": "1.6",
        "vehicleType": "SUV"
    },
    {   
        "vehicleNo": "RJ5678",
        "tripId": "TRIP0010",
        "shiftTime": "10:30",
        "shiftType": "Logout",
        "employee": "12",
        "tripStartTime": "09:45",
        "route": "Jaipur, Vaishali Nagar",
        "office": "7",
        "eta": "1.3",
        "vehicleType": "Hatchback"
    }
];
