export const safeReachConfirmationData = [
    {   
        "officeId": "OFC0001",
        "tripId": "TRIP0001",
        "shiftTime": "09:30",
        "empId": "EMP0001",
        "empName": "Hari",
        "safeReachStatus": "Failed",
        "Remarks": "15",
        "plannedSignOffTime": "9:00",
        "actualSignOffTime": "8:57",
        "updatedBy": "20240712",
        "updatedAt": "9:40",
        "action": ""
    },
    {   
        "officeId": "OFC0002",
        "tripId": "TRIP0002",
        "shiftTime": "10:00",
        "empId": "EMP0002",
        "empName": "Sara",
        "safeReachStatus": "Success",
        "Remarks": "10",
        "plannedSignOffTime": "10:30",
        "actualSignOffTime": "10:27",
        "updatedBy": "20240712",
        "updatedAt": "10:45",
        "action": ""
    },
    {   
        "officeId": "OFC0003",
        "tripId": "TRIP0003",
        "shiftTime": "08:45",
        "empId": "EMP0003",
        "empName": "John",
        "safeReachStatus": "Progress",
        "Remarks": "20",
        "plannedSignOffTime": "09:15",
        "actualSignOffTime": "09:10",
        "updatedBy": "20240712",
        "updatedAt": "09:20",
        "action": ""
    },
    {   
        "officeId": "OFC0004",
        "tripId": "TRIP0004",
        "shiftTime": "11:15",
        "empId": "EMP0004",
        "empName": "Alice",
        "safeReachStatus": "Success",
        "Remarks": "5",
        "plannedSignOffTime": "11:30",
        "actualSignOffTime": "11:29",
        "updatedBy": "20240712",
        "updatedAt": "11:35",
        "action": ""
    },
    {   
        "officeId": "OFC0005",
        "tripId": "TRIP0005",
        "shiftTime": "09:00",
        "empId": "EMP0005",
        "empName": "David",
        "safeReachStatus": "Failed",
        "Remarks": "25",
        "plannedSignOffTime": "08:30",
        "actualSignOffTime": "08:35",
        "updatedBy": "20240712",
        "updatedAt": "09:10",
        "action": ""
    },
    {   
        "officeId": "OFC0006",
        "tripId": "TRIP0006",
        "shiftTime": "10:45",
        "empId": "EMP0006",
        "empName": "Emily",
        "safeReachStatus": "Progress",
        "Remarks": "18",
        "plannedSignOffTime": "11:15",
        "actualSignOffTime": "11:18",
        "updatedBy": "20240712",
        "updatedAt": "11:30",
        "action": ""
    },
    {   
        "officeId": "OFC0007",
        "tripId": "TRIP0007",
        "shiftTime": "08:00",
        "empId": "EMP0007",
        "empName": "Michael",
        "safeReachStatus": "Success",
        "Remarks": "12",
        "plannedSignOffTime": "08:30",
        "actualSignOffTime": "08:28",
        "updatedBy": "20240712",
        "updatedAt": "08:45",
        "action": ""
    },
    {   
        "officeId": "OFC0008",
        "tripId": "TRIP0008",
        "shiftTime": "11:30",
        "empId": "EMP0008",
        "empName": "Sophia",
        "safeReachStatus": "Failed",
        "Remarks": "30",
        "plannedSignOffTime": "11:00",
        "actualSignOffTime": "11:05",
        "updatedBy": "20240712",
        "updatedAt": "11:25",
        "action": ""
    },
    {   
        "officeId": "OFC0009",
        "tripId": "TRIP0009",
        "shiftTime": "09:15",
        "empId": "EMP0009",
        "empName": "Daniel",
        "safeReachStatus": "Progress",
        "Remarks": "22",
        "plannedSignOffTime": "09:45",
        "actualSignOffTime": "09:40",
        "updatedBy": "20240712",
        "updatedAt": "10:00",
        "action": ""
    },
    {   
        "officeId": "OFC0010",
        "tripId": "TRIP0010",
        "shiftTime": "10:30",
        "empId": "EMP0010",
        "empName": "Olivia",
        "safeReachStatus": "Success",
        "Remarks": "8",
        "plannedSignOffTime": "11:00",
        "actualSignOffTime": "10:58",
        "updatedBy": "20240712",
        "updatedAt": "11:15",
        "action": ""
    }
];
