export const securityDashboardData = [
    {   
        "officeId": "OFC0001",
        "shiftType": "Login",
        "shiftTime": "09:30",
        "bookingCount": "50",
        "routingStatus": "Success",
        "dispatchStatus": "Open",
        "tripCount": "15",
        "allocatedToVendors": "10",
        "cabsDeployed": "5",
        "fleetMix": "4S:10 / 6S:3 / TT:2",
        "escortTrip": "3",
        "backToBack": "5",
        "smsStatus": "Sent",
        "emailStatus": "Pending"
    },
    {   
        "officeId": "OFC0002",
        "shiftType": "Logout",
        "shiftTime": "12:00",
        "bookingCount": "65",
        "routingStatus": "Success",
        "dispatchStatus": "Closed",
        "tripCount": "20",
        "allocatedToVendors": "15",
        "cabsDeployed": "8",
        "fleetMix": "4S:15 / 6S:5 / TT:3",
        "escortTrip": "5",
        "backToBack": "8",
        "smsStatus": "Sent",
        "emailStatus": "Sent"
    },
    {   
        "officeId": "OFC0003",
        "shiftType": "Login",
        "shiftTime": "07:45",
        "bookingCount": "40",
        "routingStatus": "Success",
        "dispatchStatus": "Open",
        "tripCount": "12",
        "allocatedToVendors": "8",
        "cabsDeployed": "4",
        "fleetMix": "4S:8 / 6S:2 / TT:2",
        "escortTrip": "2",
        "backToBack": "4",
        "smsStatus": "Sent",
        "emailStatus": "Pending"
    },
    {   
        "officeId": "OFC0004",
        "shiftType": "Login",
        "shiftTime": "10:15",
        "bookingCount": "55",
        "routingStatus": "Success",
        "dispatchStatus": "Open",
        "tripCount": "18",
        "allocatedToVendors": "12",
        "cabsDeployed": "6",
        "fleetMix": "4S:12 / 6S:3 / TT:3",
        "escortTrip": "4",
        "backToBack": "6",
        "smsStatus": "Sent",
        "emailStatus": "Sent"
    },
    {   
        "officeId": "OFC0005",
        "shiftType": "Logout",
        "shiftTime": "13:30",
        "bookingCount": "70",
        "routingStatus": "Success",
        "dispatchStatus": "Closed",
        "tripCount": "22",
        "allocatedToVendors": "18",
        "cabsDeployed": "9",
        "fleetMix": "4S:18 / 6S:6 / TT:4",
        "escortTrip": "6",
        "backToBack": "9",
        "smsStatus": "Sent",
        "emailStatus": "Sent"
    },
    {   
        "officeId": "OFC0006",
        "shiftType": "Login",
        "shiftTime": "08:00",
        "bookingCount": "45",
        "routingStatus": "Success",
        "dispatchStatus": "Open",
        "tripCount": "14",
        "allocatedToVendors": "9",
        "cabsDeployed": "5",
        "fleetMix": "4S:9 / 6S:3 / TT:2",
        "escortTrip": "3",
        "backToBack": "5",
        "smsStatus": "Sent",
        "emailStatus": "Pending"
    },
    {   
        "officeId": "OFC0007",
        "shiftType": "Logout",
        "shiftTime": "11:45",
        "bookingCount": "60",
        "routingStatus": "Success",
        "dispatchStatus": "Closed",
        "tripCount": "19",
        "allocatedToVendors": "14",
        "cabsDeployed": "7",
        "fleetMix": "4S:14 / 6S:4 / TT:3",
        "escortTrip": "5",
        "backToBack": "7",
        "smsStatus": "Sent",
        "emailStatus": "Sent"
    },
    {   
        "officeId": "OFC0008",
        "shiftType": "Login",
        "shiftTime": "09:00",
        "bookingCount": "48",
        "routingStatus": "Success",
        "dispatchStatus": "Open",
        "tripCount": "15",
        "allocatedToVendors": "11",
        "cabsDeployed": "6",
        "fleetMix": "4S:11 / 6S:3 / TT:2",
        "escortTrip": "3",
        "backToBack": "5",
        "smsStatus": "Sent",
        "emailStatus": "Pending"
    },
    {   
        "officeId": "OFC0009",
        "shiftType": "Logout",
        "shiftTime": "12:30",
        "bookingCount": "68",
        "routingStatus": "Success",
        "dispatchStatus": "Closed",
        "tripCount": "21",
        "allocatedToVendors": "17",
        "cabsDeployed": "8",
        "fleetMix": "4S:17 / 6S:5 / TT:4",
        "escortTrip": "6",
        "backToBack": "8",
        "smsStatus": "Sent",
        "emailStatus": "Sent"
    },
    {   
        "officeId": "OFC0010",
        "shiftType": "Login",
        "shiftTime": "07:30",
        "bookingCount": "38",
        "routingStatus": "Success",
        "dispatchStatus": "Open",
        "tripCount": "11",
        "allocatedToVendors": "7",
        "cabsDeployed": "4",
        "fleetMix": "4S:7 / 6S:2 / TT:2",
        "escortTrip": "2",
        "backToBack": "4",
        "smsStatus": "Sent",
        "emailStatus": "Pending"
    }
];
