export const issueTypeData = [
    {
        "empId": "E001",
        "empName": "John Doe",
        "gender": "Male",
        "pickup/dropPoint": "Downtown",
        "landmark": "City Mall",
        "vehicleReportTime": "08:00 AM",
        "signIn": "08:30 AM",
        "signOut": "05:30 PM",
        "status": "complete",
        "phoneNo": "123-456-7890",
        "action": ""
    },
    {
        "empId": "E002",
        "empName": "Jane Smith",
        "gender": "Female",
        "pickup/dropPoint": "Uptown",
        "landmark": "Central Park",
        "vehicleReportTime": "08:15 AM",
        "signIn": "08:45 AM",
        "signOut": "05:45 PM",
        "status": "complete",
        "phoneNo": "234-567-8901",
        "action": ""
    },
    {
        "empId": "E003",
        "empName": "Michael Johnson",
        "gender": "Male",
        "pickup/dropPoint": "Suburb",
        "landmark": "Green Park",
        "vehicleReportTime": "08:30 AM",
        "signIn": "09:00 AM",
        "signOut": "06:00 PM",
        "status": "incomplete",
        "phoneNo": "345-678-9012",
        "action": ""
    },
    {
        "empId": "E004",
        "empName": "Emily Davis",
        "gender": "Female",
        "pickup/dropPoint": "Downtown",
        "landmark": "Main Square",
        "vehicleReportTime": "08:00 AM",
        "signIn": "08:30 AM",
        "signOut": "05:30 PM",
        "status": "complete",
        "phoneNo": "456-789-0123",
        "action": ""
    },
    {
        "empId": "E005",
        "empName": "William Brown",
        "gender": "Male",
        "pickup/dropPoint": "Eastside",
        "landmark": "Community Center",
        "vehicleReportTime": "07:45 AM",
        "signIn": "08:15 AM",
        "signOut": "05:15 PM",
        "status": "incomplete",
        "phoneNo": "567-890-1234",
        "action": ""
    },
    {
        "empId": "E006",
        "empName": "Olivia Wilson",
        "gender": "Female",
        "pickup/dropPoint": "Westside",
        "landmark": "Library",
        "vehicleReportTime": "08:30 AM",
        "signIn": "09:00 AM",
        "signOut": "06:00 PM",
        "status": "complete",
        "phoneNo": "678-901-2345",
        "action": ""
    },
    {
        "empId": "E007",
        "empName": "James Martinez",
        "gender": "Male",
        "pickup/dropPoint": "Southside",
        "landmark": "Train Station",
        "vehicleReportTime": "08:00 AM",
        "signIn": "08:30 AM",
        "signOut": "05:30 PM",
        "status": "incomplete",
        "phoneNo": "789-012-3456",
        "action": ""
    },
    {
        "empId": "E008",
        "empName": "Sophia Anderson",
        "gender": "Female",
        "pickup/dropPoint": "Downtown",
        "landmark": "Museum",
        "vehicleReportTime": "08:15 AM",
        "signIn": "08:45 AM",
        "signOut": "05:45 PM",
        "status": "complete",
        "phoneNo": "890-123-4567",
        "action": ""
    },
    {
        "empId": "E009",
        "empName": "Liam Thomas",
        "gender": "Male",
        "pickup/dropPoint": "Uptown",
        "landmark": "Tech Park",
        "vehicleReportTime": "08:30 AM",
        "signIn": "09:00 AM",
        "signOut": "06:00 PM",
        "status": "incomplete",
        "phoneNo": "901-234-5678",
        "action": ""
    },
    {
        "empId": "E010",
        "empName": "Isabella Hernandez",
        "gender": "Female",
        "pickup/dropPoint": "Suburb",
        "landmark": "Sports Complex",
        "vehicleReportTime": "08:00 AM",
        "signIn": "08:30 AM",
        "signOut": "05:30 PM",
        "status": "complete",
        "phoneNo": "012-345-6789",
        "action": ""
    }
]
