export const allocateVendorData  = [
    {
        "tripId": "TRIP0001",
        "backToBack": "1234",
        "vehicleType": "4s",
        "firstPickup/lastDrop": "City Center",
        "zone": "Zone A",
        "noOfEmployees": "5",
        "escortStatus": "Yes",
        "special": "Yes",
        "vendorName": "",
        "vehicleNumber": "MH 01 AB 1234",
        "driverName": "John Doe"
    },
    {
        "tripId": "TRIP0002",
        "backToBack": "1234",
        "vehicleType": "6s",
        "firstPickup/lastDrop": "Central Station",
        "zone": "Zone B",
        "noOfEmployees": "7",
        "escortStatus": "No",
        "special": "No",
        "vendorName": "",
        "vehicleNumber": "KA 02 CD 5678",
        "driverName": "Jane Smith"
    },
    {
        "tripId": "TRIP0003",
        "backToBack": "1234",
        "vehicleType": "7s",
        "firstPickup/lastDrop": "East Side Mall",
        "zone": "Zone C",
        "noOfEmployees": "12",
        "escortStatus": "Yes",
        "special": "Yes",
        "vendorName": "Bharat Travels",
        "vehicleNumber": "TN 03 EF 9012",
        "driverName": "Michael Johnson"
    },
    {
        "tripId": "TRIP0004",
        "backToBack": "1234",
        "vehicleType": "12s",
        "firstPickup/lastDrop": "West End Plaza",
        "zone": "Zone D",
        "noOfEmployees": "4",
        "escortStatus": "No",
        "special": "No",
        "vendorName": "Sk Travels",
        "vehicleNumber": "UP 04 GH 3456",
        "driverName": "Emily Brown"
    },
    {
        "tripId": "TRIP0005",
        "backToBack": "1234",
        "vehicleType": "4s",
        "firstPickup/lastDrop": "North Gate",
        "zone": "Zone A",
        "noOfEmployees": "10",
        "escortStatus": "Yes",
        "special": "Yes",
        "vendorName": "World Travels",
        "vehicleNumber": "DL 05 IJ 7890",
        "driverName": "Robert Lee"
    },
    {
        "tripId": "TRIP0006",
        "backToBack": "1234",
        "vehicleType": "6s",
        "firstPickup/lastDrop": "South Park",
        "zone": "Zone B",
        "noOfEmployees": "5",
        "escortStatus": "No",
        "special": "No",
        "vendorName": "Bharat Travels",
        "vehicleNumber": "MH 06 KL 2345",
        "driverName": "Sarah Wilson"
    },
    {
        "tripId": "TRIP0007",
        "backToBack": "1234",
        "vehicleType": "7s",
        "firstPickup/lastDrop": "Downtown Square",
        "zone": "Zone C",
        "noOfEmployees": "6",
        "escortStatus": "Yes",
        "special": "Yes",
        "vendorName": "Sk Travels",
        "vehicleNumber": "KA 07 MN 6789",
        "driverName": "Christopher Martinez"
    },
    {
        "tripId": "TRIP0008",
        "backToBack": "1234",
        "vehicleType": "12s",
        "firstPickup/lastDrop": "Harbor View",
        "zone": "Zone D",
        "noOfEmployees": "7",
        "escortStatus": "No",
        "special": "No",
        "vendorName": "World Travels",
        "vehicleNumber": "TN 08 OP 1234",
        "driverName": "Amanda Davis"
    },
    {
        "tripId": "TRIP0009",
        "backToBack": "1234",
        "vehicleType": "4s",
        "firstPickup/lastDrop": "Riverside Drive",
        "zone": "Zone A",
        "noOfEmployees": "9",
        "escortStatus": "Yes",
        "special": "Yes",
        "vendorName": "Bharat Travels",
        "vehicleNumber": "UP 09 QR 5678",
        "driverName": "Daniel Garcia"
    },
    {
        "tripId": "TRIP0010",
        "backToBack": "1234",
        "vehicleType": "6s",
        "firstPickup/lastDrop": "Mountain View",
        "zone": "Zone B",
        "noOfEmployees": "12",
        "escortStatus": "No",
        "special": "No",
        "vendorName": "Sk Travels",
        "vehicleNumber": "DL 10 ST 9012",
        "driverName": "Jennifer Rodriguez"
    }
]
